<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>HamoPos.Installer</RootNamespace>
    <AssemblyName>Setup_7amo_POS</AssemblyName>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\payload.zip">
      <LogicalName>payload.zip</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

</Project>
